name: Renovate

on:
  schedule:
    - cron: "0 */3 * * *"
  #    - cron: "* 6-22/3 * * 1-5"
  #    - cron: "* 12-23/3 * * 0,6"
  push:
    branches:
      - 'main'
  issues:
    types:
      - edited
  workflow_call:
    inputs:
      runsOn:
        description: Define on which runner this workflow should run
        default: "ubuntu-latest"
        required: false
        type: string

concurrency:
  group: 'renovate'
  cancel-in-progress: false

jobs:
  renovate:
    name: Renovate
    runs-on: ${{ inputs.runsOn || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.RENOVATE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.RENOVATE_BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          mount-docker-socket: true
        env:
          RENOVATE_ALLOW_PLUGINS: true
          RENOVATE_ALLOW_SCRIPTS: true
          RENOVATE_ALLOWED_COMMANDS: "[\"git add .\"]"
          RENOVATE_AUTODISCOVER: true
          RENOVATE_BINARY_SOURCE: docker
          RENOVATE_POST_UPGRADE_TASKS: "{\"commands\": [\"git add .\"], \"fileFilters\": [\"**/*\"], \"executionMode\": \"update\"}"
          RENOVATE_DOCKER_CLI_OPTIONS: "-e=COMPOSER_IGNORE_PLATFORM_REQS=1"
          RENOVATE_DRY_RUN: "null"
          RENOVATE_IGNORE_PLUGINS: false
          RENOVATE_IGNORE_SCRIPTS: false
          RENOVATE_INTERNAL_CHECKS_FILTER: strict
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_ONBOARDING: false
          LOG_LEVEL: info
#          LOG_LEVEL: debug
#          LOG_FORMAT: json
